### ISSUE TITLE
Permission control

### ISSUE THREAD

**Issue by tobisen** [compucorp/civibooking#100]
Are there any plans on enabling access control for this. We are using it within Drupal, and there are no way I can control which will get access to the service. Other Civi components I can control through drupal's permission page.

**Comment by jamienovick** [comment]
Hi Tobisen, unfortunately CiviBooking v1.1 doesnt have any permissions structure currently, but its certainly something we would like to add. If you would be able to sponsor this development please let us know, best Jamie

**Comment by guanhuan** [comment]
Hi All,

We have just released V1.5alpha. It is a pre-release with 4.5 and 4.6 compatibility. This release also contains a new permission structure.

Feel free to try it out and report any issue back to us. Thanks in advance.

https://github.com/compucorp/civibooking/releases/tag/v1.5alpha
