### ISSUE TITLE
Disabled Resources Still Available

### ISSUE THREAD

**Issue by HeatherO** [compucorp/civibooking#101]
Hi guys,

We have an old price option that we'd like to disable. I've done so, however, it is still available to select when adding or editing a booking. 

Thanks,

Heather.

**Comment by jamienovick** [comment]
Hi Heather, we will take a look and come back to you. Which version of CiviBooking, Civi and CMS are you running?

**Comment by HeatherO** [comment]
Hi Jamie,

Thanks for that. We are on CiviCRM 4.4.3 and CiviBooking 1.1

Heather.

**Comment by SebastianBowler** [comment]
Hi Heather,

I've just tested this, and it seems fine for limited and unlimited resources. Could you provide screenshots of the relevant pages or a description you think can help isolate the issue? E.g. the new booking page, options which are available, Settings - Resource Configuration Option,  Settings - Resource Configuration Set?

Thanks,
Seb

**Comment by HeatherO** [comment]
Hi Seb,

Thanks for having a look. Basically, I went to the Resource Configuration Set page (/civicrm/admin/resource/config_set?reset=1), edited the options, and disabled the prices for tea/coffee for 2014.

![image](https://cloud.githubusercontent.com/assets/6460807/5852870/1d14a2f2-a215-11e4-95da-b38526cccae0.png)

You'll see the Tea/Coffee Full Day and Half Day 2014 options are not enabled.

Then, when you add or edit a new booking, and add an unlimited resources, the option still appear (they are first on the list):

![image](https://cloud.githubusercontent.com/assets/6460807/5852880/4489e716-a215-11e4-9261-28d8a6923a71.png)

Best wishes,

Heather.

**Comment by HeatherO** [comment]
Hi Seb,

Were you able to have a further look?

Many thanks,

Heather.

**Comment by guanhuan** [comment]
Hi Heather,

This issue should have been fixed in the latest alpha release. Please try it out in your test environment and reopen the ticket if this issue persists.
