### ISSUE TITLE
Is civibooking abandoned?

### ISSUE THREAD

**Issue by knockiiing** [compucorp/civibooking#104]
Hi,

I was wondering if civibooking project has been abandoned?

Secondly, wouldn't be good idea to convince the civicrm community to add this to the core. I cannot imagine managing an event without robust event location and resources management module. 
Thirdly, it's sad that civibooking cannot keep up with new civicrm core releases.

**Comment by petednz** [comment]
linking back to a StackExchange discussion http://civicrm.stackexchange.com/questions/4606/what-is-the-status-of-civibooking-for-civicrm-4-6-x

**Comment by guanhuan** [comment]
Hi All,

Although the development for adding the compatibility to latest CiviCRM has been running for quite a while but we are gladly announcing that we will be soon releasing CiviBooking 1.5 after a few remaining issues are fixed.

Meanwhile, feel free to try out our 1.5 alpha release in your test environment and let us know if you discovered any issue.

Much appreciated in advance.

**Comment by petednz** [comment]
thanks for the update
