### ISSUE TITLE
Issue creating new booking - blank page and no resources displayed

### ISSUE THREAD

**Issue by greenitcompany** [compucorp/civibooking#121]
I have installed the only possibly stable version of this contribution (version 1.1) on the recommended 4.4.x LTS version of Civicrm. In fact to be specific the latest 4.4.21 version. 

Everything seems to have installed well and I can use the new Booking menu options and create new resources and along with configuration sets etc... 

However when I try to create a new booking i just get an empty content section where I'm guessing the resources should be listed along with the calendar view. On inspection my Browser error Console (Firebug and google Chrome) displays the following error message:

 TypeError: scheduler.createTimelineView is not a function
http://www.domain.co.uk/civicrm/booking/add?reset=1
Line 553

Has anyone come across this before and is this an easy to resolve issue? 

Thanks in advance,

Adam

**Comment by JohnFF** [comment]
Sorry to hear you've experienced this issue. I will take a look into it for you.

**Comment by JohnFF** [comment]
Bug confirmed.

**Comment by JohnFF** [comment]
So this was caused on my local system by the resource and extension URLs not being set correctly:

http://_**YOURSITE**_/civicrm/admin/setting/updateConfigBackend?reset=1
http://_**YOURSITE**_/civicrm/admin/setting/url?reset=1

Setting them fixed the issue. Check your settings on the above pages.

**Comment by guanhuan** [comment]
Issue closed as no further detail is given. Please reopen if the issue persists.
