### ISSUE TITLE
added space after join clause

### ISSUE THREAD

**Issue by sunilpawar** [compucorp/civibooking#122]
added space after join clause, its breaking query

**Comment by guanhuan** [comment]
Hi There,

Could you confirm you CiviCRM version and Civibooking version? We will test your PR once we confirmed your fix.

**Comment by sunilpawar** [comment]
Civibooking branch : master
civicrm version : 4.6.*

**Comment by guanhuan** [comment]
Thanks.

This is assigned to our QA. We will get back to you once verified.

**Comment by guanhuan** [comment]
PR looks good. Thanks.

Merged and ticket closed.
