### ISSUE TITLE
Findbooking - error

### ISSUE THREAD

**Issue by jwgbradford** [compucorp/civibooking#131]
error msg : 
Fatal error: Access level to CRM_Booking_Form_Search::$_defaults must be public (as in class CRM_Core_Form) in /var/sites/h/hbb.org.uk/public_html/wp-content/plugins/files/civicrm/extensions/civibooking-1.5alpha/CRM/Booking/Form/Search.php on line 10

Modified:  Search.php
changed line 93 to:

  public $_defaults;

Everything now works.

**Comment by guanhuan** [comment]
Thanks John, we will verify the backwards compatibility of the fix.

Will update the ticket once complete.

**Comment by guanhuan** [comment]
Hi @jwgbradford the fix is included in the 1.5 beta release. Please verify and let us know if any problem persists.
