### ISSUE TITLE
Front end catalog and booking

### ISSUE THREAD

**Issue by jorich-2000** [compucorp/civibooking#136]
I am considering using civibooking to allow hire of equipment such as large outdoor games equipment - we have hundreds of items so it would be useful if:
There is a way of showing a front end catalog (by resource type, searchable?)
Attaching images to item descriptions

Also - how do I allow frontend Wordpress users to book items?

**Comment by guanhuan** [comment]
Hi @jorich-2000 ,

Please note that CiviBooking is currently an admin oriented tool for resource booking. Front end booking is still in the wish list.

CiviBooking currently does not have any CMS side integration for Wordpress. If you are using Drupal, there is a Drupal view integration that allows you to bring back the bookings and resources in a calendar to public https://github.com/compucorp/civiBooking_calendar.

Best regards
