### ISSUE TITLE
Support request: Upgrade from v1 to v1.5

### ISSUE THREAD

**Issue by Upperholme** [compucorp/civibooking#143]
Hi
I'm looking to upgrade a site that is currently running version 1 of this extension. Does it upgrade smoothly, or is there anything I need to take into consideration?

**Comment by guanhuan** [comment]
Hi @Upperholme , 

You should be able to upgrade to 1.5 without a problem. You might want to configure the correct permission structure afterwards as some new permissions are introduced in this version.

As for general process, it is always suggested to have a dry-run of any upgrade in a test environment prior to go live.

Best regards

**Comment by Upperholme** [comment]
Fantastic. Many thanks.
