### ISSUE TITLE
Online booking payment

### ISSUE THREAD

**Issue by sushantpaste** [compucorp/civibooking#146]
Is there any link from which user can do online booking payment ? Point me if this functionality already exits please.

**Comment by guanhuan** [comment]
Hi @sushantpaste , CiviBooking is an admin booking tool hence it does not currently support online booking nor online booking payment.

**Comment by guanhuan** [comment]
@sushantpaste if you are interested in helping implementing it, please feel free to get in touch. If you have a potential budget for this new functionality, we could look into it and give you a quote. Thanks.
