### ISSUE TITLE
Additional Text in civiBooking Resource Configuration

### ISSUE THREAD

**Issue by laurynnlowe** [compucorp/civibooking#166]
n civiBooking, additional text is showing under Resource Configurations while trying to add a booking.

Trying to add a booking, all the options (Conference Room/Hourly -$50, Conference Room/Daily -$200, Hourly - $50, Daily - $200) have the additional text /Phone or /Email added. 

Neither Phone or Email was set up as part of the resource configuration (Image 2) or size units (image 3). Where is it coming from? How do I get rid of it? 

![image 3](https://user-images.githubusercontent.com/1985014/37375811-691c4c1a-26ef-11e8-815d-700d0153bd73.png)
![image 2](https://user-images.githubusercontent.com/1985014/37375812-69328fc0-26ef-11e8-88d2-fe3ccbc7f9ae.png)
![image 1](https://user-images.githubusercontent.com/1985014/37375814-69476c4c-26ef-11e8-9088-675815f39993.png)

**Comment by laryn** [comment]
My bad for sending you here. I think I figured it out and answered on your original question:

https://civicrm.stackexchange.com/questions/23046/unintended-text-in-civibooking-resource-configuration

**Comment by laurynnlowe** [comment]
I'll close this issue, but in case other people experience the issue:
as far as I can determine, if a new unit is created, the unit value must be assigned. The default will be a number, this will cause error.
