### ISSUE TITLE
'Bookings' inline tab removed since 5.35.1 upgrade

### ISSUE THREAD

**Issue by Sez0105** [compucorp/civibooking#193]
On an organisation record, it used to have a 'bookings' on the inline tab's.
This has been removed in 5.35.1 security upgrade, can this be added back?
<img width="1260" alt="Screenshot 2021-03-24 at 11 14 47" src="https://user-images.githubusercontent.com/40298526/112301759-2e031580-8c92-11eb-9f79-3aa2efb9b34e.png">

**Comment by samuelsov** [comment]
hook_civicrm_tabs is deprecated and replaced by hook_civicrm_tabset, 

See the existing PR  https://github.com/compucorp/civibooking/pull/192/files that needs to be merged.

**Comment by erawat** [comment]
@samuelsov @samuelsov This PR https://github.com/compucorp/civibooking/pull/167 has been merged to master branch.
