### ISSUE TITLE
Error created when using discount field

### ISSUE THREAD

**Issue by HeatherO** [compucorp/civibooking#36]
When adding a booking, if you 
1. Edit the additional changes to add something
2. remove the 0.00 in the discount (i,e, backspace until null)

Then the total price updates to £NaN

You can proceed to the next page but when you save and you get the attached error and nothing is saved.
![null_error](https://f.cloud.github.com/assets/6460807/1963925/b7df2eec-82a4-11e3-8a30-958257611b8c.png)

**Comment by jamienovick** [comment]
Closed as resolved in v1.1
