### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KarinG** [compucorp/civibooking#39]
Curious - are there any plans to start expanding this to direct bookings online by members? Regards, -- Karin

**Comment by jamienovick** [comment]
Hi Karin, this is certainly something we would like to add, and is something that some clients have spoken to us about, but we are yet to find a client to fund the development. If you would be interested in funding this then we would be very pleased to discuss it.

**Comment by guanhuan** [comment]
Ticket closed as inactive.
