### ISSUE TITLE
Sample location options have a duplicate value

### ISSUE THREAD

**Issue by sgladstone** [compucorp/civibooking#43]
In the option group values for "Resource location"  ( ie booking_resource_location ) the sample data provided uses the same value for both location options. 

FYI: Would be great if the locations could be managed by a typical end-user using "Admin ... CiviBooking ... Resource Locations"

**Comment by guanhuan** [comment]
Hi There,

As resource location is a CiviCRM option group, the permission for editing it is based on the same CiviCRM permission that other admin settings are relied on. However, we are adding some permission to the extension to allow other booking related settings to be editable with the new permissions. Hopefully you can find them useful as well.
