### ISSUE TITLE
Question About posting a payment for a booking

### ISSUE THREAD

**Issue by sgladstone** [compucorp/civibooking#45]
When I am on the last step in creating a booking and am entering a payment, I do not see any way to enter a check number. (I chose payment instrument as check, but the usual box for check number is not shown) ( There are also many other entry fields missing that I normally see when creating a contribution)

Also, how do a post a partial payment such as a deposit to secure the room. (The balance is typically not due until a few weeks before the event occurs, such as after the final head count is known. Also, the fees for food/beverages may likely change if the person is having many more guests than originally planned.)

Is there a way to pay for a booking using a credit card? I have PayPalPro enabled and can submit credit card payments in the CiviCRM back-office from the "Contribution" tab.

**Comment by guanhuan** [comment]
Hi There,

CiviBooking allows admin to record contributions while making the bookings but itself does not handle any payment transactions. To add any extra payment related information, you can firstly save the contribution during the booking process and edit the contribution later.
