### ISSUE TITLE
New Resource Configuration Option bug

### ISSUE THREAD

**Issue by katiechan** [compucorp/civibooking#48]
When adding a new Resource Configuration Option, there's a tick box to choose whether you'll like the option to be enabled or not. Even if the user untick the "Enabled?" tick box, the newly saved option is saved as enabled.

**Comment by guanhuan** [comment]
Hi There,

We could not reproduce this issue on either CiviCRM 4.4 or CiviCRM 4.6. Please reopen this issue if it persists for you.
