### ISSUE TITLE
Fatal error when adding new booking

### ISSUE THREAD

**Issue by katiechan** [compucorp/civibooking#49]
In an attempt to either replicate or avoid <https://github.com/compucorp/civibooking/issues/47>. I have done a clean install of Drupal 7.26, and CiviCRM 4.4.3 on my own VPS.

Instead of the error in 47, when I try to add a new booking, I get:

"A fatal error was triggered: One of parameters (value: 1.39169042561E+12) is not of the type Integer"

**Comment by jamienovick** [comment]
Closed
