### ISSUE TITLE
Duplicate Unlimited Resources on Day View

### ISSUE THREAD

**Issue by HeatherO** [compucorp/civibooking#50]
When you edit an existing booking and edit an existing unlimited resource, all saves as expected.

When you then print the day view for that booking, each change made to the unlimited resource is listed. 

See booking id 97. There is one unlimited resource for refreshments. When you do a day view for that date (3rd January 2014) you see two unlimited resources. The first is what it was before I edited it. The second is the most recent edit.

http://civibooking.compucorp.co.uk/civicrm/booking/day-view/print?date=1388707200000&snippet=2

**Comment by jamienovick** [comment]
This has been resolved
