### ISSUE TITLE
Navigation hardcoded

### ISSUE THREAD

**Issue by tttp** [compucorp/civibooking#53]
Hi,

The way you handle the navigation menu items (in the hook) makes it impossible to rename/move/disable/whatever you usually do with menues).

Moreover, it has an "interesting" side effect: as there isn't any id because it doesn't come from the , if you try to edit a booking menu item, it will either try to change the nav id=0 (doesn't exist) or id=1 (home page, reserved and big mess if you touch it)

It would be better instead of using that hook to add the menu items in the navigation table (not sure if the api entity is added yet in the core, I've seen some code to handle it), and let users manage it like the others.

X+

**Comment by knockiiing** [comment]
Hi, do you have any update on this issue?

**Comment by guanhuan** [comment]
Hi Xavier,

We have modified the menu mechanism to automatically use the next index to the largest index used in the system. However, I think flexibility of moving the menu is still absent. Please feel free to reopen this issue if there is currently any better way available to handle this.
