### ISSUE TITLE
Create booking doesn't call pre and post hooks

### ISSUE THREAD

**Issue by tttp** [compucorp/civibooking#77]
Meine liebe caramels, 

on CRM_Booking_BAO_Booking::create
you should add a pre and post hook call

Where should I PR? You seem to do all the work on the release 1-1 branch that is ahead on master?

X+

**Comment by guanhuan** [comment]
Hi Xavier,

I know that this issue has been here for quite a while. Just in case you are still interested, please reopen and send your PR to the develop branch.

(We are now adapting the git workflow here: http://nvie.com/posts/a-successful-git-branching-model/ but modified to fit our work process)

Much appreciated.
