### ISSUE TITLE
Can't load CiviBooking screens on clean install of 1.1

### ISSUE THREAD

**Issue by MegaphoneJon** [compucorp/civibooking#91]
Sorry if this isn't the appropriate place for it...let me know if there's a better place!
I installed CiviBooking 1.1, and none of the pages will load, either Admin or Booking pages.  Clicking on a menu items (other than those linking to OptionGroup edit pages) gives the same result as if you put in a page that doesn't exist.  

I've tried installing CiviBooking from the extensions directory and from git, on two separate Civi installations on different servers, both running 4.4.5.

There's no errors showing, nothing in ConfigAndLog, nothing in Apache's error.log.  I'm not sure what I'm doing wrong or how I can troubleshoot to submit a more helpful bug report!

**Comment by harked** [comment]
Hi. I've had the same problem while installing civicrm 4.4.14 alongside drupal 7.25. 
Then after installing civibooking 1.1, you should try to rebuild menu.
The step is : go to http://your_site/civicrm/menu/rebuild?reset=1

change your site with your cms site url.
