### ISSUE TITLE
Menu is broken on CiviCRM 4.5.2 & Joomla 2.5.27.

### ISSUE THREAD

**Issue by jorich-2000** [compucorp/civibooking#97]
After several installs of civibooking 1.1 , rebuild menus, clear caches, etc I still have problem where menu is not working.  eg url from menu item is https://iwww.org.uk/administrator/?option=com_civicrm&task=civicrm/booking/add_reset_1  - underscores instead of other characters.

https://iwww.org.uk/administrator/?option=com_civicrm&task=civicrm/booking/add&reset=1 works fine

this applies to the booking and admin->civibooking menu
previous post simply thi si sfixed but it does not appear to be

**Comment by pailong** [comment]
This is due to an error syntax in Civibooking code in booking.php.
To correct it change the first & to ? in urls
For example 'url' => 'civicrm/booking/add&reset=1' becomes 'url' => 'civicrm/booking/add?reset=1',

**Comment by jorich-2000** [comment]
Fabulous - that answered the issue - I un-installed the extension, edited about 5 lines in the file - re-installed and it works perfectly
