### ISSUE TITLE
Issues booking a resource under 4.5.5 (CiviBooking version 1.1)

### ISSUE THREAD

**Issue by sgladstone** [compucorp/civibooking#99]
I am having 2 related issues running under CiviCRM version 4.5.5 (upgraded from version 4.4.7)

When I add a resource to my booking, the colored box is only about 3 pixels wide, and it does not allow me to expand it to the start/end times I prefer.  

After clicking it, the dialog box I expect opens. BUT, it just spins and spins and does not show anything in the dialog box. 

I have added 2 screen prints of this issue

![cannot_expand_timeslot_issue](https://cloud.githubusercontent.com/assets/2640984/5601500/bcffc50c-92d0-11e4-8e89-a314729fc833.png)
![add_resource_issue](https://cloud.githubusercontent.com/assets/2640984/5601501/c4038d16-92d0-11e4-944f-53b382e16cc7.png)

**Comment by francispoisson** [comment]
Same here.

Civibooking 1.1
CiviCRM version 4.5.5
Wordpress 4.1

**Comment by tttp** [comment]
Same on drupal

The error messages (on the popup) seems to be linked to a missing underscore library. 
eg: 
     var template = _.template(cj('#add-resource-template').html());
     *TypeError: _ is undefined*

**Comment by jamienovick** [comment]
Hi all, unfortunately we are still working on the 4.5 support for CiviBooking. If you have an urgent need to use CiviBooking we are maintaining the support for the v4.4 of CiviCRM currently and we will release an update as soon as v4.5 support is completed.

**Comment by guanhuan** [comment]
Hi All,

We have just released V1.5alpha. It is a pre-release with 4.5 and 4.6 compatibility.
https://github.com/compucorp/civibooking/releases/tag/v1.5alpha

Feel free to try it out and report any issue back to us. Thanks in advance.
